[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"
buildCommand = "echo 'Building Django API for production'"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:$PORT time_tracking_backend.wsgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { DJANGO_ENV = "production" }
