blank_issues_enabled: false
contact_links:
  - name: 💬 CS Club Discord
    url: https://discord.gg/vR3y4heZ
    about: Get help from the community in real-time
  - name: 📧 Email Support
    url: mailto:scsucsciclub@gmail.com
    about: Contact the CS Club officers directly